spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://database-1.cjoem2sqkwdj.ap-south-1.rds.amazonaws.com:3306/jrtp23
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

  mail:
    host: smtp.gmail.com
    port: 587
    username: khanshahrukh7910@gmail.com
    password: qhvgvdkspnhzkumk
    properties.mail.smtp:
        auth: true
        starttls.enable: true
   
      
      